apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redskyops
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    control-plane: controller-manager
  name: "{{ .Release.Name }}-controller-manager"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/name: redskyops
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        redskyops.dev/secretHash: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/name: redskyops
        app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        envFrom:
        - secretRef:
            name: "{{ .Release.Name }}-manager"
            optional: true
        image: "{{ .Values.redskyImage }}:{{ .Values.redskyTag }}"
        imagePullPolicy: {{ .Values.redskyImagePullPolicy }}
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
      terminationGracePeriodSeconds: 10
