annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/namespace: kong
  catalog.cattle.io/release-name: kong
apiVersion: v1
appVersion: "2"
description: The Cloud-Native Ingress and API-management
home: https://konghq.com/
icon: https://s3.amazonaws.com/downloads.kong/universe/assets/icon-kong-inc-large.png
maintainers:
- email: harry@konghq.com
  name: hbagdi
- email: traines@konghq.com
  name: rainest
name: kong
version: 1.8.000
